# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

# The theme colour scheme to use. Valid values are congo (default), avocado, ocean, fire and slate.
colorScheme = "slate"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = false

mainSections = ["samples"]
# robots = ""

[header]
  layout = "basic" # valid options: basic, hamburger, hybrid, custom
  # logo = "img/logo.jpg"
  showTitle = true

[footer]
  showCopyright = false
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = false

[homepage]
  layout = "custom" # valid options: page, profile, custom
  showRecent = false

[article]
  showDate = false
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = false
  editURL = "https://github.com/jpanther/congo/tree/dev/exampleSite/content/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = false
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = false
  showWordCount = false
  showComments = false
  # sharingLinks = ["facebook", "twitter", "pinterest", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = true
  showSummary = false
  showTableOfContents = true
  showTaxonomies = false
  groupByYear = false
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
